### ISSUE TITLE
Equipo PyCon 2020

### ISSUE THREAD

**Issue by arendondiosa** [PyConColombia/website-2020#26]
Conformar Equipo 2019 para la Web
URL: `/equipo` - `/en/team`

```
- [ ] Nombre
  - [ ] _Nombre de Usuario (URL para perfil en la web)_: 
  - [ ] _Foto:_
  - [ ] _Web:_ 
  - [ ] _Email:_ 
  - [ ] _Facebook:_ 
  - [ ] _Twitter:_ 
  - [ ] _GitHub:_
  - [ ] _LinkedIn:_
  - [ ] _Equipo:_ e.g. Chief Organizer, Web, Redes Sociales
  - [ ] _Rol:_ Organizador, Colaborador o Voluntario
  - [ ] _Summary_:
```

**Comment by MiltonLn** [comment]
- [x] Nombre: Milton Lenis 
  - [x] _Foto:_  ![milton](https://user-images.githubusercontent.com/7388681/66137514-d2872880-e5c2-11e9-8fd1-08306973b366.jpg)

  - [x] _Web:_ https://miltonlenis.com
  - [x] _Email:_ miltonln04@gmail.com
  - [ ] _Facebook:_ 
  - [x] _Twitter:_ https://twitter.com/MiltonLn
  - [x] _GitHub:_ https://github.com/MiltonLn
  - [x] _LinkedIn:_ https://www.linkedin.com/in/miltonln/
  - [ ] _Equipo:_ Speakers
  - [ ] _Rol:_ Organizador

**Comment by arendondiosa** [comment]
- [X] Nombre: Alejandro E. Rendon
  - [X] _Foto:_ 
![photo_bg_square](https://user-images.githubusercontent.com/14989202/66255601-23c22400-e74b-11e9-9b4e-ec2c49c4568a.png)

  - [X] _Web:_ https://rendon.co 
  - [X] _Email:_ alejandro@rendon.co
  - [ ] _Facebook:_ 
  - [X] _Twitter:_ arendondiosa 
  - [X] _GitHub:_ arendondiosa
  - [X] _LinkedIn:_ arendondiosa
  - [ ] _Equipo:_ e.g. Web
  - [ ] _Rol:_ Organizador

**Comment by karobotco** [comment]
- [x] Nombre: Karolina Ladino Puerto
  - [x] _Foto:_ ![alt text](https://scontent-bog1-1.xx.fbcdn.net/v/t1.0-9/66848892_2251625328208504_8177954920876474368_n.jpg?_nc_cat=106&_nc_oc=AQkEbXaYaGGmFU7pa8ev-q90w5kreC--VEdfOxU7kUGBzyMqbwi2Mhs3Cqg31tq7m2s&_nc_ht=scontent-bog1-1.xx&oh=94e85c95a7d6f82f625bdae60a95bd81&oe=5E1B38B0 "Karobot Foto")
  - [x] _Web:_ https://karobot.co
  - [x] _Email:_ ladinokarolina@gmail.com
  - [x] _Facebook:_ https://twitter.com/karobotco
  - [x] _Twitter:_ https://twitter.com/karobotco
  - [x] _GitHub:_ https://github.com/KaroLadino
  - [x] _LinkedIn:_ https://www.linkedin.com/in/karobot/
  - [x] _Equipo:_ Sponsors
  - [x] _Rol:_ Colaboradora

**Comment by carogomezt** [comment]
- [ ] Carolina Gómez Trejos
  - [ ] _Foto:_ 
![carolina-gomez](https://user-images.githubusercontent.com/17128791/67219379-8410c100-f3ed-11e9-8770-569e71aedb08.jpg)

  - [ ] _Web:_ https://carogomezt.github.io/
  - [ ] _Email:_ carolina9511@gmail.com
  - [ ] _Facebook:_ https://www.facebook.com/carogomezt
  - [ ] _Twitter:_ https://twitter.com/caro_gomezt
  - [ ] _GitHub:_ https://github.com/carogomezt
  - [ ] _LinkedIn:_ https://www.linkedin.com/in/carolinagomezt/
  - [ ] _Equipo:_ Django Girls Colombia
  - [ ] _Rol:_ Colaboradora

**Comment by leonartromo** [comment]
- [x] Nombre: Leonardo Romo
  - [x]  Foto: 
![IMG_20190902_165623759](https://user-images.githubusercontent.com/35345382/67643709-424db200-f8e8-11e9-8d6a-57a71bffaeb7.jpg)
  - [ ]  Web:_ 
  - [x]  Email: leonardromo04@gmail.com
  - [x]  Facebook: https://www.facebook.com/Leoromo97
  - [x]  Twitter: https://twitter.com/Leoromo97
  - [x]  GitHub: https://github.com/leonartromo
  - [x]  LinkedIn: https://linkedin.com/in/leonardo-romo-808616103/
  - [x]  Equipo: Redes Sociales
  - [x]  Rol: Colaborador

**Comment by isaquinva** [comment]
- [ ] Nombre: Isabella Quintana
  - [ ] _Foto: https://www.dropbox.com/s/cxjwyz285aclkqk/Isabella%20Quintana-500px.jpg?dl=0
  - [ ] _Web: https://www.behance.net/isaquinva
  - [ ] _Email: isaquinva@gmail.com
  - [ ] _Facebook: -
  - [ ] _Twitter: https://twitter.com/isaquinva
  - [ ] _GitHub: 
  - [ ] _LinkedIn: https://www.linkedin.com/in/isabella-quintana
  - [ ] _Equipo: Comunicación / Redes Sociales
  - [ ] _Rol: Colaboradora
  - [ ] _Summary_: Diseñadora Gráfica / Graphic Designer

**Comment by EngAndres** [comment]
- [ ] Nombre Carlos Andrés Sierra Virgüez
  - [ ] _Nombre de Usuario (URL para perfil en la web)_: casierrav
  - [ ] _Foto:_ https://scontent.fbog10-1.fna.fbcdn.net/v/t1.0-9/s960x960/53754242_10156096352318085_1473014434946351104_o.jpg?_nc_cat=111&_nc_oc=AQmNnuJ35TdIzDjhSzhBGwpRlzAGgiUI0LEZ-SL6urRbm84Msjsc_NdEHkru5kxRod8&_nc_ht=scontent.fbog10-1.fna&oh=7f8ceec1d241ec98608ce80533893cbf&oe=5E53E4B9
  - [ ] _Web:_ 
  - [ ] _Email:_  carlos.andres.sierra.v@gmail.com
  - [ ] _Facebook:_ 
  - [ ] _Twitter:_  @casierrav_alife
  - [ ] _GitHub:_  www,github.com/engandres
  - [ ] _LinkedIn:_ https://www.linkedin.com/in/casierrav/
  - [ ] _Equipo:_ Speakers / Sponsors
  - [ ] _Rol:_ Organizador

**Comment by estebanx64** [comment]
- [x] Nombre: Esteban Maya
  - [x] Foto: https://avatars2.githubusercontent.com/u/10840422?s=460&v=4
  - [ ] Web: 
  - [x] Email: emayacadavid9@gmail.com
  - [x] Facebook: https://www.facebook.com/estebanx64
  - [x] Twitter: https://twitter.com/esteban_x64
  - [x] GitHub: https://github.com/estebanx64
  - [x] LinkedIn: https://www.linkedin.com/in/esteban-maya-cadavid-10346051/
  - [x] Equipo: Keynotes
  - [x] Rol: Organizador

**Comment by davoshack** [comment]
- [ ] Nombre: Juan David Hernández Giraldo
- [ ] Web: https://medium.com/@JuanDHernandezG
- [ ] Foto https://drive.google.com/file/d/1LDwMkFI3R4nji54JXjD_ULHGYqdY9dr8/view?usp=sharing
- [ ] Email: juandhernandez2008@gmail.com
- [ ] GitHub: https://github.com/davoshack
- [ ] Twitter: https://twitter.com/JuanDHernandezG
- [ ] Linkedin: https://www.linkedin.com/in/juandhernandez/
- [ ] Equipo: Venue
- [ ] Rol: Organizador
